"use client";

import { ContactList, Navbar } from "@/components";
import { RoomProvider } from "@/providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RoomsLayout({ children }: { children: React.ReactNode }) {
	return (
		<RoomProvider>
			<section className="overflow-hidden">
				<main className="h-screen w-screen bg-gray-950 flex flex-col">
					<Navbar type={"app"} />
					<div className="flex overflow-y-auto h-full">
						<ContactList />
						{children}
					</div>
				</main>
			</section>
		</RoomProvider>
	);
}
