"use client";

import "./globals.css";
import { ApiProvider, SocketProvider, UserProvider } from "@/providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<ApiProvider>
				<body className="h-screen w-screen bg-gradient-to-bl from-indigo-950 to-sky-950">
					<SocketProvider>
						<UserProvider>{children}</UserProvider>
					</SocketProvider>
				</body>
			</ApiProvider>
		</html>
	);
}
